import { Options } from './types';
export default class Night {
    private elements;
    private settings;
    private callbacks;
    private isInit;
    private isDark;
    private isPlaying;
    private coords;
    private autoCoords;
    private times;
    private autoTimes;
    private matchLight;
    private matchDark;
    private today;
    constructor(data?: Options);
    private init;
    private isNight;
    private changeClasses;
    private ambientLight;
    private sound;
    light(): void;
    dark(): void;
    private prefersColorScheme;
    smartSwitch(isInit?: boolean): void;
    private time;
    private theme;
    private switchOnChange;
    private myLocation;
    private accessSuccess;
    private accessError;
    private sunPosition;
    private timeBreakpoints;
    setCoords(latitude: number, longitude: number): void;
    setTimes(sunrise: number, sunset: number): void;
    toggle(): void;
    reset(): void;
    destroy(): void;
    private extendSettings;
}
